apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
 
  annotations:
    monitoring: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - image: kube/demo_app_new:v2
        name: demo-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4047
       